version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - make dev-deploy
# artifacts:
#   type: zip
#   files:
#     - server/packaged-template.yml
#     - server/test-stack-configuration.json
#   discard-paths: yes
